### ISSUE TITLE
Support monorepos

### ISSUE THREAD

**Issue by astrodomas** [opennextjs/opennextjs-cloudflare#111]
Hello, I couldn't find any discussions on this repo.

A question I have is regarding monorepo setups. For example there are many projects that use `nrwl/nx` or `lerna` will (is it even possible?) this package be able to support these setups?

**Comment by tadhglewis** [comment]
I'm using a monorepo, works fine.

**Comment by ruqqq** [comment]
@tadhglewis how are you setting up the .npmrc or the workspace? I'm using pnpm and seems to be running issues with `cloudflare` cmd, whilst `next build` works fine.

Seems to be complaining while it is trying to patch wrangler: `# patchWranglerDeps`

**Comment by eli-front** [comment]
I'm still having issues with related. Anyone have a working example with pnpm + turborepo? Works completely fine if I remove the `pnpm-workspace.yaml`, but won't work with the symlinks.
