### ISSUE TITLE
How to access environment variables?

### ISSUE THREAD

**Issue by ubergonmx** [opennextjs/opennextjs-cloudflare#125]
Coming from Vercel trying to convert a project to use `@opennextjs/cloudflare` just to try it out for the first time, I have my env setup like this for typesafety:
```
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DISCORD_CLIENT_ID: z.string().trim().min(1),
    DISCORD_CLIENT_SECRET: z.string().trim().min(1),
    ...
  },
  client: { NEXT_PUBLIC_APP_URL: z.string().url() },
  runtimeEnv: {
    DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    ...
  },
  emptyStringAsUndefined: true,
});
```

Everything works fine locally, ran `npm run dev` and it uses my `.env` and `npm run preview` which uses `.dev.vars` .
However, when deployed to Workers (via GitHub CI/CD), it wont build because it cant find it even though I already added my environment variables to **Settings > Variables and Secrets** using the Dashboard
```
02:05:27.537 | ❌ Invalid environment variables: {
02:05:27.538 | DISCORD_CLIENT_ID: [ 'Required' ],
02:05:27.538 | DISCORD_CLIENT_SECRET: [ 'Required' ],
02:05:27.542 | NEXT_PUBLIC_APP_URL: [ 'Required' ]
02:05:27.542 | }
02:05:27.542 | Error: Invalid environment variables
```

How do I fix this?

My deploy command in the Build Configuration is `npm run deploy` instead of `npx wrangler deploy`

**Comment by Karibash** [comment]
@ubergonmx 
You can obtain it by using getCloudflareContext as shown below.

```ts
import { getCloudflareContext } from '@opennextjs/cloudflare';

const { env } = await getCloudflareContext();
```

**Comment by ubergonmx** [comment]
> @ubergonmx You can obtain it by using getCloudflareContext as shown below.
> 
> ```ts
> import { getCloudflareContext } from '@opennextjs/cloudflare';
> 
> const { env } = await getCloudflareContext();
> ```

No this doesn't work 
`Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', 'node16', 'nodenext', or 'preserve', and the 'target' option is set to 'es2017' or higher.`

**Comment by ubergonmx** [comment]
> @ubergonmx You can obtain it by using getCloudflareContext as shown below.
> 
> ```ts
> import { getCloudflareContext } from '@opennextjs/cloudflare';
> 
> const { env } = await getCloudflareContext();
> ```

Doing this, I have to add `target` in tsconfig.json with the value `es2017`. Now I get the following error when running locally using `npm run preview` (as well as in deployment).

The error is:
```
Failed to compile.

./node_modules\next\dist\compiled\server-only\index.js
'server-only' cannot be imported from a Client Component module. It should only be used from a Server Component.

Import trace for requested module:
  ./node_modules\next\dist\compiled\server-only\index.js
  ./node_modules\@opennextjs\cloudflare\dist\api\chunk-VTBEIZPQ.mjs
  ./node_modules\@opennextjs\cloudflare\dist\api\index.mjs
  ./src\env.ts
  ./src\lib\utils.ts
  ./src\components\ui\accordion.tsx
```

Is there a way to fix this?

**Comment by vicb** [comment]
I would suggest to add a minimal repro demonstrating the issue. There is not much we can do to help with a few lines of codes and an error log only.

At first sight it doesn't really look like it's related to this package. Maybe you can also ask on discord.

Hope this makes sense.

**Comment by pondorasti** [comment]
> I would suggest to add a minimal repro demonstrating the issue. There is not much we can do to help with a few lines of codes and an error log only.
> 
> At first sight it doesn't really look like it's related to this package. Maybe you can also ask on discord.
> 
> Hope this makes sense.

As far as I can tell, most, **if not all**, Next.js apps running on Node.js are going to run into this issue. This comes down to the differences of using envs, `process.env` vs `async getCloudflareContext`. Take for example https://github.com/t3-oss/create-t3-app which is likely a similar setup to @ubergonmx code example that uses https://github.com/t3-oss/t3-env.

If you need further evidence, a similar problem has also been reported on Cloudflare's community with no resolution: 
https://community.cloudflare.com/t/next-js-worker-not-finding-environment-variables/727147

Is there a way for `@opennextjs` to polyfill `process.env` at build time? I feel that if `@opennextjs` wants to be successful, there must be a middle ground of keeping backwards compatibility. I'm personally looking to migrate https://emojis.sh/ from Vercel to Cloudflare Workers. Ideally for a smooth migration, I would still like to deploy on both platforms until I gain confidence that everything works just as well and fast on Cloudflare.

**Comment by ubergonmx** [comment]
> I would suggest to add a minimal repro demonstrating the issue. There is not much we can do to help with a few lines of codes and an error log only.
> 
> At first sight it doesn't really look like it's related to this package. Maybe you can also ask on discord.
> 
> Hope this makes sense.

I'll try to reproduce this in a new repo starting from the opennextjs template but for the meantime, here's my [repo](https://github.com/ubergonmx/usabilitree-cloudflare) and the [recent commit](https://github.com/ubergonmx/usabilitree-cloudflare/commit/8148f384638b4a060680d9f29341bc20ad9f71c4) I did to use `getCloudflareContext()`. 

Currently here's my workaround:
I have a hono repo deployed to workers, and I have a GET request that requires a key query and returns the environment variables as a plain text. 
```
app.get("/env", async (c) => {
  if (c.req.query("key") !== undefined && c.req.query("key") === c.env.SECRET_KEY) {
    const { DB, SECRET_KEY, ...env } = c.env;
    const envText = Object.entries(env)
      .map(([key, value]) => `${key}=${value}`)
      .join("\n");
    return c.text(envText);
  }
});
```
and then in the build command in the Build Configuration, I have set it to the following:
`curl -o .env https://hono.mywebsite.com/env?key=<secret-key>`

**Comment by vicb** [comment]
> This comes down to the differences of using envs, process.env vs async getCloudflareContext ...

I am very aware of the confusion. See the discussion I initiated [there](https://github.com/cloudflare/workers-sdk/discussions/7180).

We are [currently doing](https://github.com/opennextjs/opennextjs-cloudflare/blob/26509ca7456028f36b33e8625680db49c373b07e/packages/cloudflare/src/cli/templates/worker.ts#L39):

```ts
globalThis.process.env = { ...globalThis.process.env, ...env };
```

while I feel like we shouldn't be doing this (as it exposes secrets to any library via `process.env`), I expect this to "solve' your issue. But again we can not investigate without a minimal repro.

> I'll try to reproduce this in a new repo starting from the opennextjs template when I have the time.

Same here: I don't have time.

And it's nothing against you. 

I literally gave the same answer to my manager asking me to support a customer earlier today. Sure I can take time to work on a given issue but that is time I will not be spending on fixing the issue globally. 

[We say](https://opennext.js.org/cloudflare#:~:text=%F0%9F%92%A1-,%40opennextjs/cloudflare,don%27t%20quite%20yet%20recommend%20using%20it%20for%20mission%2Dcritical%20production%20apps.,-You%20can%20also):

> @opennextjs/cloudflare is pre 1.0, and still in active development. You should try it, report bugs, share feedback, and contribute code to help make running Next.js apps on Cloudflare easier. We don't quite yet recommend using it for mission-critical production apps.

Our target is to have a solid product in the coming weeks. Having minimal repro of the issue you currently face will help us get there but we can not afford to debug full app.

**Comment by ubergonmx** [comment]
I see, thank you for transparency and for the work you're doing on opennextjs @vicb

As for the error, I fixed `'server-only' cannot be imported from a Client Component module. It should only be used from a Server Component.` Since I believe `getCloudflareContext` can't be used in client components, it is caused by my utils.ts where I have `cn` (function used for tailwind; shadcn) and `absoluteUrl`  which imports this env. 

Since cn is used in a client component (accordion.tsx) and absoluteUrl is server-side, I fixed it by separating absoluteUrl into its own file.

However, the error `Invalid environment variables` from my main post still appears.

**Comment by ubergonmx** [comment]
@vicb 

I’ve created a minimal reproduction of the issue to help clarify. Here’s how I set it up:

- Started with `npm create cloudflare@latest -- . --framework=next --experimental` and installed `@t3-oss/env-nextjs` and `zod`.
- Added `target: "ES2017"` to `tsconfig.json`.
- Created `env.ts` in `src/`:

    ```typescript
    import { getCloudflareContext } from "@opennextjs/cloudflare";
    import { createEnv } from "@t3-oss/env-nextjs";
    import { z } from "zod";

    const { env: cfEnv } = await getCloudflareContext();

    export const env = createEnv({
      server: {
        DEMO: z.string().trim().min(1),
      },
      client: {},
      runtimeEnv: {
        DEMO: cfEnv.DEMO,
      },
      emptyStringAsUndefined: true,
    });
    ```

- Set up `.dev.vars` with `DEMO=hello` and added `DEMO: string;` in `env.d.ts`.
- Imported `env` in `app/page.tsx` and ran `npm run preview`—everything worked fine locally.
- Deployed to Workers connected to Git, with:
  - **Build command:** `npx cloudflare`
  - **Deploy command:** `npx wrangler deploy`
- Added the `DEMO` secret in **Variables and Secrets** in the Settings, and re-deployed (CI/CD).

You can check out the [repo](https://github.com/ubergonmx/opennextjs-env) and the [build log](https://github.com/ubergonmx/opennextjs-env/blob/master/logs/opennextjs-env.production.6824e7ae-43ce-422d-8a75-26b642356df2.build.log) for more details.

**Comment by pondorasti** [comment]
> > This comes down to the differences of using envs, process.env vs async getCloudflareContext ...
> 
> I am very aware of the confusion. See the discussion I initiated [there](https://github.com/cloudflare/workers-sdk/discussions/7180).
> 
> We are [currently doing](https://github.com/opennextjs/opennextjs-cloudflare/blob/26509ca7456028f36b33e8625680db49c373b07e/packages/cloudflare/src/cli/templates/worker.ts#L39):


This is awesome and works as expected! Turns out that my problem was related to Worker configuration, I had my envs added to runtime secrets rather than build time secrets.

## ❌ Before

![CleanShot 2024-11-07 at 12 55 40@2x](https://github.com/user-attachments/assets/0931aaea-2069-4424-882f-9cd8e07309f7)

## ✅ After

![CleanShot 2024-11-07 at 12 57 12@2x](https://github.com/user-attachments/assets/a745e5cf-c16c-4d19-a447-08212109f2ee)


----



> > @opennextjs/cloudflare is pre 1.0, and still in active development. You should try it, report bugs, share feedback, and contribute code to help make running Next.js apps on Cloudflare easier. We don't quite yet recommend using it for mission-critical production apps.
> 
> Our target is to have a solid product in the coming weeks.

exciting!

**Comment by ubergonmx** [comment]
> Turns out that my problem was related to Worker configuration, I had my envs added to runtime secrets rather than build time secrets.

I tried doing that now to the minimal repro but it still doesn't work :\
