### ISSUE TITLE
[BUG] module.findSourceMap is not implemented yet!

### ISSUE THREAD

**Issue by abel3t** [opennextjs/opennextjs-cloudflare#135]
### Describe the bug

When I try `dev:worker`, I found these errors:
On Terminal: ✘ [ERROR] <Formatting threw (Error: [unenv] module.findSourceMap is not implemented yet!

Browser:
```bash
Error: The script will never generate a response.
    at async Object.fetch (file:///{mypath}/node_modules/miniflare/dist/src/workers/core/entry.worker.js:1029:22)
```

### Steps to reproduce

1. I use Kinde sdk for nextjs in middleware
2. Setup `@opennextjs/cloudflare`
3. Run `dev:worker`

### Expected behavior

On Terminal: ✘ [ERROR] <Formatting threw (Error: [unenv] module.findSourceMap is not implemented yet!

Browser:
```bash
Error: The script will never generate a response.
    at async Object.fetch (file:///{mypath}/node_modules/miniflare/dist/src/workers/core/entry.worker.js:1029:22)
```

### @opennextjs/cloudflare version

0.2.1

### Node.js version

20.8.1

### Wrangler version

3.78.10

### next info output

```shell
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 712.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.1/bin/npm
    pnpm: 8.6.10 - ~/Library/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 131.1.73.89
    Chrome: 130.0.6723.117
    Safari: 18.0.1
```

**Comment by vicb** [comment]
> I use Kinde sdk for nextjs in middleware

What is your setup - this is not enough information to reproduce.
Also note that middleware is not yet supported on the main branch - middleware support is being implemented in the experimental branch.

> `Error: [unenv] module.findSourceMap is not implemented yet!`

`findSourceMap` is not implemented as source paths (and map paths) do not make sense for workers as we don't have access to the file system. unenv should probably return undefined.
