### ISSUE TITLE
[BUG] I have a question related to cloudflare page&works cpu billing

### ISSUE THREAD

**Issue by zhaoyunyi** [opennextjs/opennextjs-cloudflare#146]
### Describe the bug

Hey, all. May be it's not a bug. I created a project with opennextjs-cloudflare and published it to cloudflare pages & works without any changes. I tried to access the project a couple of times and got some metrics about the project and found that the CPU time is much higher than the free plan for Cloudflare works, which has a 10 cpu limit, but the project is accessing fine and not reporting errors, why is this? If a completely initial nextjs project has problems deploying to cloudflare pages & works, what is the point of cloudflare pages & works? Thanks for the help.

![image](https://github.com/user-attachments/assets/1dc0897b-1ee2-4dc8-9339-6fb588d82a04)

### Steps to reproduce

none

### Expected behavior

none

### @opennextjs/cloudflare version

0.2.1

### Node.js version

20.9

### Wrangler version

3.91.0

### next info output

```shell
none
```

**Comment by vicb** [comment]
Could you please add more information about what project you are deploying and the URL you hit?
It will help us investigate.
Thanks

**Comment by vicb** [comment]
Then I'm closing this issue for now.

Feel free to re-open if this is still a problem
