### ISSUE TITLE
Roadmap of progression

### ISSUE THREAD

**Issue by JohnAntonios** [opennextjs/opennextjs-cloudflare#164]
Hi there,

I'm very interested in the progress of this package as I would like to use Cloudflare Workers with Next.js 15.

Is there any roadmap / timeline that can be referenced or when this will reach 1.0?

Thanks!

**Comment by vicb** [comment]
You can see the progress at https://github.com/orgs/opennextjs/projects/1/views/2

Current timeline is pre-1.0 by early 2025. At that point we should have a better idea of what's missing for 1.0 and be able to give a timeline.

I hope this helps.
