### ISSUE TITLE
[BUG] The build process requires a custom not-found page to be defined

### ISSUE THREAD

**Issue by dario-piotrowicz** [opennextjs/opennextjs-cloudflare#167]
### Describe the bug

I have a very minimalistic Next.js 14 app with only an api route, when trying to build my application using the adapter the build process fails with the following error unless I provide a custom not-found page:
![Screenshot 2024-12-12 at 13 13 45](https://github.com/user-attachments/assets/ff9dbbee-ece3-4f5e-8a99-1447ad1c4874)

### Steps to reproduce

- pull down the code here: https://github.com/dario-piotrowicz/next-14-hello-world-app/tree/open-next
- run `npm run build:worker` and see that the build succeeds
- delete the `app/not-found.tsx`
- run `npm run build:worker` and see the build failing

### Expected behavior

I don't think a custom not-found page should be mandatory

### @opennextjs/cloudflare version

https://pkg.pr.new/@opennextjs/cloudflare@experimental

### Node.js version

20.11.0

### Wrangler version

3

### next info output

```shell
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 9.12.1
Relevant Packages:
  next: 14.2.6 // An outdated version detected (latest is 15.1.0), upgrade is highly recommended!
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Additional context

Not too important, but when forced to create a custom not-found page I then also need to have a root layout (https://github.com/dario-piotrowicz/next-14-hello-world-app/blob/open-next/app/layout.tsx), meaning that I actually need to add two unnecessary files to my app

**Comment by vicb** [comment]
@conico974 any thoughts/hints here?

**Comment by vicb** [comment]
Thank you so much @conico974 

@dario-piotrowicz, would you mind validating the fix in pnpm add https://pkg.pr.new/@opennextjs/aws@674?

**Comment by dario-piotrowicz** [comment]
> @dario-piotrowicz, would you mind validating the fix in https://pkg.pr.new/@opennextjs/aws@674?

Done 👍

**Comment by vicb** [comment]
Thanks @dario-piotrowicz!
I'll close this after the aws dep is updated
