### ISSUE TITLE
[BUG] 404 - on experimental branch with Nextjs 15.1

### ISSUE THREAD

**Issue by himanshu-ntml** [opennextjs/opennextjs-cloudflare#172]
### Describe the bug

I updated Next.js to the latest version on an experimental branch, and now I’m getting 404 errors everywhere.

### Steps to reproduce

1) clone https://github.com/himanshu-ntml/opennext-15
2) npm run preview

### Expected behavior

Should work as expected

### @opennextjs/cloudflare version

experimental

### Node.js version

v22.11.0

### Wrangler version

3.95.0

### next info output

```shell
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 22.11.0
  npm: 10.9.0
  Yarn: 1.22.22
  pnpm: 9.12.3
Relevant Packages:
  next: 15.1.0 // Latest available version is detected (15.1.0).
  eslint-config-next: 14.2.5
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

**Comment by vicb** [comment]
> I updated Next.js to the latest version on an experimental branch, and now I’m getting 404 errors everywhere.

What Next version did you use before, was it working?

**Comment by himanshu-ntml** [comment]
It was running on Next.js 14.2.11, which is the default version when you create a new app following the OpenNext documentation.

I updated it to next 15 by following next docs here is the [link](https://nextjs.org/blog/next-15)

Let me know if you need anything else.

I appreciate all the work you putting into making nextjs compatible with Cloudflare.

**Comment by dario-piotrowicz** [comment]
@himanshu-ntml a fix is on its way 😄 : https://github.com/opennextjs/opennextjs-cloudflare/pull/184

If you want please give the [PR's prerelease](https://github.com/opennextjs/opennextjs-cloudflare/pull/184#issuecomment-2549449685) a try and let me know if it works for you 🙂

**Comment by himanshu-ntml** [comment]
Thank you so much for such a quick solution. Yes, trying it right now

**Comment by himanshu-ntml** [comment]
It works perfectly—thank you so much for all the work you guys are putting into this!
