### ISSUE TITLE
[BUG]: Next.js 15 + middleware causes `__import_unsupported` error

### ISSUE THREAD

**Issue by dario-piotrowicz** [opennextjs/opennextjs-cloudflare#177]
### Describe the bug

If I have an Next.js app that is on Next.js 15 and has a middleware, the adapter can build the application but at runtime the application throws a `__import_unsupported` error:
![Screenshot 2024-12-15 at 19 17 56](https://github.com/user-attachments/assets/4bca1bf3-27c1-48fb-b16d-c4491b1f4c10)

### Steps to reproduce

- Create a new Next.js 15 application
- Install the adapter (the experimental release)
- add a middleware file
- build and preview the application
- navigate to the application's url to see the error

Minimal reproduction: https://github.com/dario-piotrowicz/open-next-15-middleware-experimental-repro

### Expected behavior

The application should just work

### @opennextjs/cloudflare version

https://pkg.pr.new/@opennextjs/cloudflare@experimental

### Node.js version

20

### Wrangler version

3

### next info output

```shell
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 9.12.1
Relevant Packages:
  next: 15.1.0 // Latest available version is detected (15.1.0).
  eslint-config-next: 14.2.5
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Additional context

#141 implements a simple fix for this

but: 
 - the fix should be done properly with AST manipulation
 - we should understand better why this issue gets triggered and if the proposed patch is the appropriate solution

**Comment by conico974** [comment]
We already have a fix for this in aws but at the moment it's not applied to cloudflare https://github.com/opennextjs/opennextjs-aws/blob/697681bf9ce25212ce4e2e94d886ca425428280d/packages/open-next/src/build/edge/createEdgeBundle.ts#L141-L147. Just moving this a few line up should be enough.

This happens when the middleware runs in the same place as the main handler.
They use `defineProperty` for `__import_unsupported` both in the middleware and in the main server but they define it with `configurable:false`

**Comment by dario-piotrowicz** [comment]
Great, thanks for the context @conico974 😄 

Ah ok, so you're saying that this is a fix to be made in the aws package and that we'll then inherit right? 🙂 
I'm happy to give it a go unless you want to take it on 😄

**Comment by conico974** [comment]
I could do it tomorrow if you want, but if you want to do it in the meantime feel free to do so

**Comment by dario-piotrowicz** [comment]
> I could do it tomorrow if you want, but if you want to do it in the meantime feel free to do so

https://github.com/opennextjs/opennextjs-aws/pull/678 🙂

**Comment by dario-piotrowicz** [comment]
Reopening until this is merged to main

**Comment by vicb** [comment]
> Reopening until this is merged to main

Added to the [Done (experimental branch)](https://github.com/orgs/opennextjs/projects/1/views/2) column
