### ISSUE TITLE
Yarn Support

### ISSUE THREAD

**Issue by vacom** [opennextjs/opennextjs-cloudflare#45]
Hey, I'm trying to install this package (following the Getting Started guide from https://opennext.js.org/cloudflare/get-started) on an existing project that uses Yarn v1.22.18. However, the build fails because it seems to require PNPM. Is this an intentional design choice, or will the package support other package managers like Yarn?

This also happens with NPM if npm is set on the packageManager  on package.json

```
UsageError: This project is configured to use yarn because package.json has a "packageManager" field
    at Engine.findProjectSpec (.....)

Node.js v22.6.0
node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: pnpm next build```

**Comment by cmackenzie1** [comment]
Facing this issue as well but trying to use just `npm` instead of `pnpm`

**Comment by dario-piotrowicz** [comment]
Hi @vacom, thanks for the issue 🙂 

The fact that `pnpm` is being used to build the application is something we put in just for the same of quickly implementing the prototype it's not a intentional design choice/restriction.

I've opened #49 which should hopefully address this, both for `yarn` and `npm` (and `bun`)

**Comment by vacom** [comment]
It's no longer complaining because of yarn, it's entering in the build process, only now it's getting the same error that someone opened here https://github.com/opennextjs/opennextjs-cloudflare/issues/42

Thanks for the fix!

**Comment by dario-piotrowicz** [comment]
@vacom thanks for confirming that it works now 😄 

I'll be looking into #42 tomorrow 👍
