### ISSUE TITLE
Setting `type` to `module` in `package.json` causes runtime errors

### ISSUE THREAD

**Issue by Karibash** [opennextjs/opennextjs-cloudflare#47]
### Summary

Setting `type` to `module` in `package.json` causes runtime errors.

### Steps to Reproduce

1. Set up the project using `npm create cloudflare@latest -- my-next-app --framework=next --experimental`.
2. Modify `package.json` to set `"type": "module"`.
3. Run `npm run deploy` to deploy the project.

### Expected Behavior

There should be no errors when the page is displayed.

### Actual Behavior

A runtime error occurs when calling `new import_next_server.default()`.

### Possible Cause

When calling `new import_next_server.default()`, I get an error `default is not a constructor`.
The error suggests that `import_next_server.default` is not imported correctly.

Before setting `type` to `module`, the code is:

```javascript
var import_next_server = __toESM(require_next_server());
```

After setting `type` to `module`, the code changes to:

```javascript
var import_next_server = __toESM(require_next_server(), 1);
```

**Comment by dario-piotrowicz** [comment]
Hi @Karibash, thanks for the issue 🙂 

Just to understand things better, and sorry if this is a silly question 😅, why would you want to set the `type` to `module` in your `package.json`? what's the use case?

**Comment by Karibash** [comment]
Hi @dario-piotrowicz, thank you for your prompt reply.

By setting the type to "module", you can make `.js` files be treated as ESM. This allows you to use `.js` instead of `.mjs` when creating ESLint FlatConfig or Vitest Config. I prefer using this option frequently as it helps avoid mixing different file extensions like `.mjs` and `.js`.

**Comment by dario-piotrowicz** [comment]
Ah.... ok I didn't know this was something require to use `.js` and esm in eslint or vitest (yeah it does make sense I guess 🤔) 

Thanks for clarifying this, I will have a look 🙂👍

**Comment by dario-piotrowicz** [comment]
@Karibash a fix is on its way 😄

**Comment by dario-piotrowicz** [comment]
@Karibash please try the latest release: [`0.0.0-59a1d9e`](https://www.npmjs.com/package/@opennextjs/cloudflare/v/0.0.0-59a1d9e) and let me know if it's all good now 😄

**Comment by Karibash** [comment]
@dario-piotrowicz thank you for the correction. I have confirmed that it is working properly!

**Comment by dario-piotrowicz** [comment]
awesome! thanks for confirming that 😄
