### ISSUE TITLE
Build Error: # patchCached

### ISSUE THREAD

**Issue by justindjeumenet** [opennextjs/opennextjs-cloudflare#56]
@dario-piotrowicz as per your request please! Thank you

Next.js build correctly without any issues but Cloudflare fails at this level:

# patchCached
file:///Users/justindjeumene/WebstormProjects/ixxxxxxxxxxx/node_modules/@opennextjs/cloudflare/dist/cli/index.mjs:6860
    throw new Error("Cache patch not applied");
          ^

Error: Cache patch not applied

Here is my wrangler.toml
#:schema node_modules/wrangler/config-schema.json
name = "xxxxxxxx-clouflare"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "xxxxxxxxxxx1e"

Here is the cloudflare that fails:
// src/cli/build/patches/investigated/patch-cache.ts
import path7 from "node:path";
function patchCache(code, config) {
  console.log("# patchCached");
  const cacheHandler = path7.join(config.paths.internalPackage, "cli", "cache-handler.mjs");
  const patchedCode = code.replace(
    "const { cacheHandler } = this.nextConfig;",
    `const cacheHandler = null;
CacheHandler = (await import('${cacheHandler}')).default;
CacheHandler.maybeKVNamespace = process.env["${config.cache.kvBindingName}"];
`
  );
  if (patchedCode === code) {
    throw new Error("Cache patch not applied");
  }
  return patchedCode;
}

**Comment by vicb** [comment]
What version of Next are you using?
Can you reproduce the issue on a minimal app that you can share?

**Comment by justindjeumenet** [comment]
Hey @vicb!
I am using next.js v14.0.4, I just started a very minimal project with the latest next.js and that error went away. I was having that error because I was integrating cloudflare in my existing project....I think that is why.
I can close this ticket saying a minimal project works without issues.
Thanks
