### ISSUE TITLE
Is there anyway to get Prisma ORM to work with this, Using Native Postgres

### ISSUE THREAD

**Issue by gregavola** [opennextjs/opennextjs-cloudflare#71]
It appears there are some missing Node file reads, but I'm wondering if there is anyway to get this working with Prisma. This fails anytime we call the Prisma Client.

"Error: [unenv] fs.readdir is not implemented yet!",

**Comment by vicb** [comment]
I don't think your issue is related to open next - but to running Prisma on workers.

You can check [the docs](https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-cloudflare) and ask questions on the cloudflare discord if you need help. It's always better to have a minimal repro when asking for help.

Does it make sense?

**Comment by gregavola** [comment]
Sorry - I should have noted and provided an example repo. The reason why I asked if that this repo intent was allow NextJS apps to run on the node runtime on Workers. I assumed that since Prisma worked on nodejs - that this would do the same.

It appears that Prisma isn't compatible as it's still needs fs - which isn't available in the runtime.

I guess I misunderstood what this package's goals were. Everything else worked perfectly except for a native db connection with Prisma.

I didn't know if there was a workaround for these type of things.

**Comment by vicb** [comment]
> I assumed that since Prisma worked on nodejs - that this would do the same.
> It appears that Prisma isn't compatible as it's still needs fs - which isn't available in the runtime.

Prisma works on workers.

You  can check the [Prisma docs](https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-cloudflare) and [cloudflare docs](https://developers.cloudflare.com/d1/tutorials/d1-and-prisma-orm).

The thing is that you probably do not have the correct setup for Prisma and that's why I'm directing you the [discord](https://discord.com/invite/cloudflaredev) to get help with your setup.

**Comment by vicb** [comment]
@gregavola do you think you can close that issue and handle that in the workerd discussion (see #76)?

**Comment by gregavola** [comment]
I added it here: https://github.com/cloudflare/workerd/discussions/2858 Thanks

**Comment by gregavola** [comment]
I will say this, that I've done a bit research and it's appears to be related to the OpenNext build process. I've swapped this out for serverless NeonDB, and it runs locally fun, but when it's deployed to CloudFlare Workers, it's the same issue here.

I've tested a sample of just a basic workers project with Prisma, that wasn't part of the OpenNext and it works fine without any issues. There are docs that work fine as you provided but once I build the app with next build, and then deploy with wrangler, it errors out with this.

```


09:58:49.035 | ✘ [ERROR] Could not resolve "#main-entry-point"
-- | --
09:58:49.035 |  
09:58:49.035 | .worker-next/.next/standalone/node_modules/.prisma/client/default.js:1:30:
09:58:49.035 | 1 │ module.exports = { ...require('#main-entry-point') }
09:58:49.035 | ╵                               ~~~~~~~~~~~~~~~~~~~
09:58:49.035 |  
09:58:49.036 | The module "./wasm.js" was not found on the file system:
09:58:49.036 |  
09:58:49.036 | .worker-next/.next/standalone/node_modules/.prisma/client/package.json:114:19:
09:58:49.036 | 114 │         "workerd": "./wasm.js",
09:58:49.036 | ╵                    ~~~~~~~~~~~
09:58:49.036 |  
09:58:49.036 | You can mark the path "#main-entry-point" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
09:58:49.036 |  
09:58:49.038 |  
09:58:49.038 |  
09:58:49.039 | ✘ [ERROR] Could not resolve "#main-entry-point"
09:58:49.040 |  
09:58:49.040 | .worker-next/.next/standalone/node_modules/.prisma/client/default.js:1:30:
09:58:49.040 | 1 │ module.exports = { ...require('#main-entry-point') }

```

**Comment by vicb** [comment]
I added a ref back to this issue on the discussion. Thanks for moving it there.

**Comment by voxxit** [comment]
I am encountering the same as the above: `Error: [unenv] fs.readdir is not implemented yet!`

**Comment by km5x2** [comment]
Add this to your nextjs config 

`serverExternalPackages: ["@prisma/client", ".prisma/client"]. `

https://opennext.js.org/cloudflare/howtos/db
