### ISSUE TITLE
Support for middleware

### ISSUE THREAD

**Issue by SamyPesse** [opennextjs/opennextjs-cloudflare#92]
We currently use `next-on-pages` for https://github.com/GitbookIO/gitbook; we'd love to migrate it to opennext to solve a few problems with Cloudflare Pages, mainly the fact that a CF Pages can't be used as a SSL-For-SaaS target.

It looks like the only thing that is blocking us at the moment is the lack of middleware support.

**Comment by vicb** [comment]
It's coming, stay tuned!

**Comment by victorkardel** [comment]
up, any ETA ?

**Comment by eliahilse** [comment]
Great! Also eagerly waiting here :)

**Comment by brenden-js** [comment]
Any updates? Patiently awaiting!

**Comment by vicb** [comment]
There is some support in the experimental branch. More to come this week

**Comment by pellicceama** [comment]
We would also love this :)

**Comment by vitorbal** [comment]
Would love to see this land soon! I'm building a Nextjs app entirely on CF workers and middleware support is the last remaining puzzle piece for auth with Clerk :)

**Comment by vicb** [comment]
Yep you can try the middleware support on the experimental branch, see https://github.com/opennextjs/opennextjs-cloudflare?tab=readme-ov-file#preleases and https://github.com/opennextjs/opennextjs-cloudflare/blob/experimental/packages/cloudflare/README.md

**Comment by dandoen** [comment]
Great to see it close to landing. I tried it on my project just now and am getting a 500 internal server error with the following log:
> Error: Middleware is not supported in minimal mode. Please remove the `NEXT_MINIMAL` environment variable.

Presumably due to https://github.com/opennextjs/opennextjs-cloudflare/blob/8502d6298889f2916f38b702e49cb90073166e07/packages/cloudflare/src/cli/build/build-worker.ts#L96

**Comment by vicb** [comment]
> Great to see it close to landing @vicb. I tried it on my project just now and am getting a 500 internal server error with the following log:

Please open another issue and attach a minimal repro in a repository.

The `middleware` example in the experimental branch works.

**Comment by vitorbal** [comment]
yeah, I had a similar issue to @dandoen . I was scratching my head for a few minutes until I realized the experimental branch builds to `.open-next/worker.ts`, but the config from the tutorial in https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/  points to `.worker-next/index.mjs`.

Still testing it out but so far looks 💯 . Thanks @vicb!

**Comment by vicb** [comment]
Sorry for the confusion. 
I liked the experilental readme in my previous message but i reckon it's hard to track all the changes. 
I'm wondering if we should detect such mismatch but at the same time we hope to merge back the experimental branch next week.

**Comment by pellicceama** [comment]
Amazing! Will try it!

**Comment by vicb** [comment]
Middleware support has been merged into main and released in 0.3.0

Feel free to re-open if you still have issues
