### ISSUE TITLE
Support for `waitUntil` from `@vercel/functions`

### ISSUE THREAD

**Issue by nathanclevenger** [opennextjs/opennextjs-cloudflare#96]
To allow more compatibility between NextJS on Cloudflare for applications coming from Vercel, it would be extremely helpful if the `waitUntil` function `@vercel/functions` (https://vercel.com/docs/functions/vercel-functions-package#waituntil) could be mapped to `getCloudflareContext().ctx.waitUntil` 

Is this possible?  And if so, is this planned or on the roadmap?

**Comment by shashankboosi** [comment]
Hey @nathanclevenger, 

I was going through the workers documentation and I can see that in their context API they already support the use of `waitUntil` function as seen [here](https://developers.cloudflare.com/workers/runtime-apis/context/) but I don't know if the implementation from the `@vercel/functions` is the same. Hopefully both of them would have adapted this from the waitUntil used in [service workers](https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil). I hope this helps!

**Comment by vicb** [comment]
This was merged in main / release 0.3.0.

Feel free to re-open if you still have issues.
